# Generated by Django 3.2.12 on 2023-04-16 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_user_donor_blood_bank_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCertificate',
            fields=[
                ('donation_certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('camp_name', models.CharField(max_length=30)),
                ('date', models.CharField(default='N/A', max_length=30, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
